apiVersion: v1
kind: Service
metadata:
  name: studentapp-service
  namespace: student
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30011
  selector:
    app: studentapp-pod
